<?php

use Illuminate\Database\Seeder;

class ProyectoTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //proyecto
        DB::table('proy_proyecto')->insert([
            [
                'proy_estado'                     => 5,
                'proy_nombre'                     => 'MEJORAMIENTO DE LA CAPACIDAD RESOLUTIVA DEL HOSPITAL DE TINGO MARIA - PROVINCIA LEONCIO PRADO - REGION HUANUCO',
                'proy_cod_snip'                   => 51581,
                'proy_cod_siaf'                   => 2094811,
                'funcion_id'                      => 2,
                'proy_funcion'                    => 'SALUD',
                'proy_beneficiarios'              => 42115,
                'ubigeo_id'                       => 518,
                'proy_localidad'                  => 'TINGO',
                'proy_pip_actualizado'            => 175343744.04,
                'proy_perfil_viable'              => 90371211.00,
                'proy_snip15'                     => 108287327.93,
                'proy_snip16'                     => 108287328.00,
                'admin_administrador'             => 2,
                'proy_tipo_proyecto'              => 2,
                'proy_fte_fto'                    => 'RECURSOS ORDINARIOS',
                'proy_pim'                        => '[{"anio":"2010","pim":2412092},{"anio":"2011","pim":2711892},{"anio":"2012","pim":30384403},{"anio":"2013","pim":61374424},{"anio":"2014","pim":495823},{"anio":"2015","pim":17808456}]',
                'proy_act_sosem'                  => '2019-01-01 15:30:03',
                'proy_ejecucion_otras_ejecutoras' => 0.00,
                'proy_act_ejecucion'              => '2019-01-01 20:00:17',
            ],
            [
                'proy_estado'                     => 9,
                'proy_nombre'                     => 'MEJORAMIENTO DE LA CAPACIDAD RESOLUTIVA DE LOS SERVICIOS DE SALUD DEL HOSPITAL REGIONAL HERMILIO VALDIZAN DE HUANUCO-NIVEL III-1',
                'proy_cod_snip'                   => 133630,
                'proy_cod_siaf'                   => 2130855,
                'funcion_id'                      => 2,
                'proy_funcion'                    => 'SALUD',
                'proy_beneficiarios'              => 780411,
                'ubigeo_id'                       => 621,
                'proy_localidad'                  => 'esperanza',
                'proy_pip_actualizado'            => 199622589.66,
                'proy_perfil_viable'              => 157064036.00,
                'proy_snip15'                     => 0.00,
                'proy_snip16'                     => 171551206.00,
                'admin_administrador'             => 2,
                'proy_tipo_proyecto'              => 2,
                'proy_fte_fto'                    => 'RECURSOS ORDINARIOS',
                'proy_pim'                        => '[{"anio":"2012","pim":1900000},{"anio":"2013","pim":551658},{"anio":"2014","pim":19542050},{"anio":"2015","pim":25640764},{"anio":"2016","pim":4838397}]',
                'proy_act_sosem'                  => '2019-01-01 15:30:07',
                'proy_ejecucion_otras_ejecutoras' => 0.00,
                'proy_act_ejecucion'              => '2019-01-01 20:00:24',
            ],
        ]);

        DB::table('proy_analitico')->insert([
            [
                'ana_act_proy'         => 2094811,
                'ana_componente'       => 2207833,
                'ana_especifca'        => 'ACbcxQ9',
                'ana_monto'            => 2649875.50,
                'ana_modificaciones'   => null,
                'ana_descricion'       => 'EJECUTADO NO PROGRAMADO',
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2094811,
                'ana_componente'       => 4000003,
                'ana_especifca'        => 'ACbcxQ9',
                'ana_monto'            => 360955.84,
                'ana_modificaciones'   => null,
                'ana_descricion'       => null,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2094811,
                'ana_componente'       => 4000003,
                'ana_especifca'        => 'ACbJvAN',
                'ana_monto'            => 7940.00,
                'ana_modificaciones'   => null,
                'ana_descricion'       => null,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2094811,
                'ana_componente'       => 4000014,
                'ana_especifca'        => 'ACbF63O',
                'ana_monto'            => 81188738.57,
                'ana_modificaciones'   => null,
                'ana_descricion'       => 'costo directo',
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2094811,
                'ana_componente'       => 4000014,
                'ana_especifca'        => 'ACbF63P',
                'ana_monto'            => 201453.24,
                'ana_modificaciones'   => null,
                'ana_descricion'       => null,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2094811,
                'ana_componente'       => 4000014,
                'ana_especifca'        => 'ACbF63Q',
                'ana_monto'            => 9750.00,
                'ana_modificaciones'   => null,
                'ana_descricion'       => null,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2094811,
                'ana_componente'       => 4000014,
                'ana_especifca'        => 'ACbF63R',
                'ana_monto'            => 73027.70,
                'ana_modificaciones'   => null,
                'ana_descricion'       => null,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2094811,
                'ana_componente'       => 4000014,
                'ana_especifca'        => 'ACbJu9G',
                'ana_monto'            => 2540.00,
                'ana_modificaciones'   => null,
                'ana_descricion'       => null,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2094811,
                'ana_componente'       => 4000014,
                'ana_especifca'        => 'ACbJvAN',
                'ana_monto'            => 3679.64,
                'ana_modificaciones'   => null,
                'ana_descricion'       => null,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2094811,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbcxQ9',
                'ana_monto'            => 9967.20,
                'ana_modificaciones'   => null,
                'ana_descricion'       => null,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2094811,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbF63O',
                'ana_monto'            => 60792695.00,
                'ana_modificaciones'   => null,
                'ana_descricion'       => null,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2094811,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbF63P',
                'ana_monto'            => 92033.30,
                'ana_modificaciones'   => null,
                'ana_descricion'       => null,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2094811,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbF63Q',
                'ana_monto'            => 25178.47,
                'ana_modificaciones'   => null,
                'ana_descricion'       => null,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2094811,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbF63R',
                'ana_monto'            => 73417.70,
                'ana_modificaciones'   => null,
                'ana_descricion'       => null,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2094811,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJu9F',
                'ana_monto'            => 1290.00,
                'ana_modificaciones'   => null,
                'ana_descricion'       => null,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2094811,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJu9G',
                'ana_monto'            => 700.00,
                'ana_modificaciones'   => null,
                'ana_descricion'       => null,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2094811,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJvAN',
                'ana_monto'            => 10914.25,
                'ana_modificaciones'   => null,
                'ana_descricion'       => null,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2094811,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJvAP',
                'ana_monto'            => 6200.00,
                'ana_modificaciones'   => null,
                'ana_descricion'       => null,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2094811,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJvJl',
                'ana_monto'            => 3499.00,
                'ana_modificaciones'   => null,
                'ana_descricion'       => null,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2094811,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbVI++',
                'ana_monto'            => 10000.00,
                'ana_modificaciones'   => null,
                'ana_descricion'       => null,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2094811,
                'ana_componente'       => 6000002,
                'ana_especifca'        => 'ACbF61t',
                'ana_monto'            => 0.00,
                'ana_modificaciones'   => null,
                'ana_descricion'       => 'SERVICIOS',
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2094811,
                'ana_componente'       => 6000002,
                'ana_especifca'        => 'ACbF63O',
                'ana_monto'            => 4244579.90,
                'ana_modificaciones'   => null,
                'ana_descricion'       => null,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2094811,
                'ana_componente'       => 6000005,
                'ana_especifca'        => 'ACbJvBy',
                'ana_monto'            => 20385627.82,
                'ana_modificaciones'   => null,
                'ana_descricion'       => null,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2094811,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbF63P',
                'ana_monto'            => 613926.29,
                'ana_modificaciones'   => null,
                'ana_descricion'       => null,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2094811,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbF63Q',
                'ana_monto'            => 59270.88,
                'ana_modificaciones'   => null,
                'ana_descricion'       => null,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2094811,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbF63R',
                'ana_monto'            => 902928.43,
                'ana_modificaciones'   => null,
                'ana_descricion'       => null,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2094811,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbJu9F',
                'ana_monto'            => 13873.45,
                'ana_modificaciones'   => null,
                'ana_descricion'       => null,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2094811,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbJu9G',
                'ana_monto'            => 1800.00,
                'ana_modificaciones'   => null,
                'ana_descricion'       => null,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2094811,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbJvAN',
                'ana_monto'            => 36976.14,
                'ana_modificaciones'   => null,
                'ana_descricion'       => null,
                'analitico_version_id' => 1,
            ],
        ]);

        DB::table('proy_analitico')->insert([
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbF63O',
                'ana_monto'            => 74551589.17,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbF63P',
                'ana_monto'            => 2114504.20,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbF63R',
                'ana_monto'            => 3070428.38,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000002,
                'ana_especifca'        => 'ACbF63P',
                'ana_monto'            => 196726.23,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000002,
                'ana_especifca'        => 'ACbF63O',
                'ana_monto'            => 4527841.38,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000001,
                'ana_especifca'        => 'ACbcxQ9',
                'ana_monto'            => 2605849.63,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbF63P',
                'ana_monto'            => 514919.13,
                'ana_modificaciones'   => 34715.87,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbF63Q',
                'ana_monto'            => 150145.28,
                'ana_modificaciones'   => -21724.99,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbF63R',
                'ana_monto'            => 1208212.96,
                'ana_modificaciones'   => 2308936.31,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbF63Q',
                'ana_monto'            => 1843808.31,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJu9F',
                'ana_monto'            => 3598.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJu9G',
                'ana_monto'            => 590.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJu+p',
                'ana_monto'            => 20381.25,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJvAN',
                'ana_monto'            => 16732.56,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJvBx',
                'ana_monto'            => 1000.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJvBy',
                'ana_monto'            => 26789.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJvJp',
                'ana_monto'            => 1800.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbcxQ9',
                'ana_monto'            => 292546.33,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000007,
                'ana_especifca'        => 'ACbF63O',
                'ana_monto'            => 43137178.08,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000007,
                'ana_especifca'        => 'ACbF63R',
                'ana_monto'            => 1378274.21,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000007,
                'ana_especifca'        => 'ACbcxQ9',
                'ana_monto'            => 162864.23,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbF61u',
                'ana_monto'            => 9769421.56,
                'ana_modificaciones'   => -2326378.68,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000001,
                'ana_especifca'        => 'ACbJvAN',
                'ana_monto'            => 4474.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000002,
                'ana_especifca'        => 'ACbF63Q',
                'ana_monto'            => 5420.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000002,
                'ana_especifca'        => 'ACbF63R',
                'ana_monto'            => 24645.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbJu9F',
                'ana_monto'            => 15100.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbJvAN',
                'ana_monto'            => 7670.00,
                'ana_modificaciones'   => 851.49,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbcxQ9',
                'ana_monto'            => 11000.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000005,
                'ana_especifca'        => 'ACbJu+p',
                'ana_monto'            => 44567835.30,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbJu9G',
                'ana_monto'            => 22600.00,
                'ana_modificaciones'   => 3600.00,
                'analitico_version_id' => 1,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000007,
                'ana_especifca'        => 'ACbcxQ9',
                'ana_monto'            => 162864.23,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000007,
                'ana_especifca'        => 'ACbF63O',
                'ana_monto'            => 43137178.08,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000007,
                'ana_especifca'        => 'ACbF63R',
                'ana_monto'            => 1378274.21,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbcxQ9',
                'ana_monto'            => 292546.33,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbF61u',
                'ana_monto'            => 9769421.56,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbF63O',
                'ana_monto'            => 74551589.17,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbF63P',
                'ana_monto'            => 2114504.20,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbF63Q',
                'ana_monto'            => 1843808.31,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbF63R',
                'ana_monto'            => 3070428.38,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJu+p',
                'ana_monto'            => 20381.25,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJu9F',
                'ana_monto'            => 3598.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJu9G',
                'ana_monto'            => 590.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJvAN',
                'ana_monto'            => 16732.56,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJvBx',
                'ana_monto'            => 1000.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJvBy',
                'ana_monto'            => 26789.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJvJp',
                'ana_monto'            => 1800.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000001,
                'ana_especifca'        => 'ACbcxQ9',
                'ana_monto'            => 2605849.63,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000001,
                'ana_especifca'        => 'ACbJvAN',
                'ana_monto'            => 4474.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000002,
                'ana_especifca'        => 'ACbF63O',
                'ana_monto'            => 4527841.38,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000002,
                'ana_especifca'        => 'ACbF63P',
                'ana_monto'            => 196726.23,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000002,
                'ana_especifca'        => 'ACbF63Q',
                'ana_monto'            => 5420.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000002,
                'ana_especifca'        => 'ACbF63R',
                'ana_monto'            => 24645.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000005,
                'ana_especifca'        => 'ACbJu+p',
                'ana_monto'            => 44567835.30,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbcxQ9',
                'ana_monto'            => 11000.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbF63P',
                'ana_monto'            => 514919.13,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbF63Q',
                'ana_monto'            => 150145.28,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbF63R',
                'ana_monto'            => 1208212.96,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbJu9F',
                'ana_monto'            => 15100.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbJu9G',
                'ana_monto'            => 22600.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbJvAN',
                'ana_monto'            => 7670.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 44,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000007,
                'ana_especifca'        => 'ACbcxQ9',
                'ana_monto'            => 162864.23,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000007,
                'ana_especifca'        => 'ACbF63O',
                'ana_monto'            => 43137178.08,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000007,
                'ana_especifca'        => 'ACbF63R',
                'ana_monto'            => 1378274.21,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbcxQ9',
                'ana_monto'            => 292546.33,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbF61u',
                'ana_monto'            => 9769421.56,
                'ana_modificaciones'   => -2326378.68,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbF63O',
                'ana_monto'            => 74551589.17,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbF63P',
                'ana_monto'            => 2114504.20,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbF63Q',
                'ana_monto'            => 1843808.31,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbF63R',
                'ana_monto'            => 3070428.38,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJu+p',
                'ana_monto'            => 20381.25,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJu9F',
                'ana_monto'            => 3598.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJu9G',
                'ana_monto'            => 590.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJvAN',
                'ana_monto'            => 16732.56,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJvBx',
                'ana_monto'            => 1000.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJvBy',
                'ana_monto'            => 26789.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJvJp',
                'ana_monto'            => 1800.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000001,
                'ana_especifca'        => 'ACbcxQ9',
                'ana_monto'            => 2605849.63,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000001,
                'ana_especifca'        => 'ACbJvAN',
                'ana_monto'            => 4474.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000002,
                'ana_especifca'        => 'ACbF63O',
                'ana_monto'            => 4527841.38,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000002,
                'ana_especifca'        => 'ACbF63P',
                'ana_monto'            => 196726.23,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000002,
                'ana_especifca'        => 'ACbF63Q',
                'ana_monto'            => 5420.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000002,
                'ana_especifca'        => 'ACbF63R',
                'ana_monto'            => 24645.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000005,
                'ana_especifca'        => 'ACbJu+p',
                'ana_monto'            => 44567835.30,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbcxQ9',
                'ana_monto'            => 11000.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbF63P',
                'ana_monto'            => 514919.13,
                'ana_modificaciones'   => 34715.87,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbF63Q',
                'ana_monto'            => 150145.28,
                'ana_modificaciones'   => -21724.99,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbF63R',
                'ana_monto'            => 1208212.96,
                'ana_modificaciones'   => 2308936.31,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbJu9F',
                'ana_monto'            => 15100.00,
                'ana_modificaciones'   => -3600.00,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbJu9G',
                'ana_monto'            => 22600.00,
                'ana_modificaciones'   => -22600.00,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbJvAN',
                'ana_monto'            => 7670.00,
                'ana_modificaciones'   => 30651.49,
                'analitico_version_id' => 77,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000007,
                'ana_especifca'        => 'ACbcxQ9',
                'ana_monto'            => 162864.23,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 78,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000007,
                'ana_especifca'        => 'ACbF63O',
                'ana_monto'            => 43137178.08,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 78,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000007,
                'ana_especifca'        => 'ACbF63R',
                'ana_monto'            => 1378274.21,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 78,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbcxQ9',
                'ana_monto'            => 292546.33,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 78,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbF61u',
                'ana_monto'            => 9769421.56,
                'ana_modificaciones'   => -2326378.68,
                'analitico_version_id' => 78,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbF63O',
                'ana_monto'            => 74551589.17,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 78,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbF63P',
                'ana_monto'            => 2114504.20,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 78,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbF63Q',
                'ana_monto'            => 1843808.31,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 78,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbF63R',
                'ana_monto'            => 3070428.38,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 78,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJu+p',
                'ana_monto'            => 20381.25,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 78,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJu9F',
                'ana_monto'            => 3598.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 78,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJu9G',
                'ana_monto'            => 590.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 78,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJvAN',
                'ana_monto'            => 16732.56,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 78,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJvBx',
                'ana_monto'            => 1000.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 78,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJvBy',
                'ana_monto'            => 26789.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 78,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 4000015,
                'ana_especifca'        => 'ACbJvJp',
                'ana_monto'            => 1800.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 78,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000001,
                'ana_especifca'        => 'ACbcxQ9',
                'ana_monto'            => 2605849.63,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 78,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000001,
                'ana_especifca'        => 'ACbJvAN',
                'ana_monto'            => 4474.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 78,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000002,
                'ana_especifca'        => 'ACbF63O',
                'ana_monto'            => 4527841.38,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 78,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000002,
                'ana_especifca'        => 'ACbF63P',
                'ana_monto'            => 196726.23,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 78,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000002,
                'ana_especifca'        => 'ACbF63Q',
                'ana_monto'            => 5420.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 78,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000002,
                'ana_especifca'        => 'ACbF63R',
                'ana_monto'            => 24645.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 78,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000005,
                'ana_especifca'        => 'ACbJu+p',
                'ana_monto'            => 44567835.30,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 78,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbcxQ9',
                'ana_monto'            => 11000.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 78,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbF63P',
                'ana_monto'            => 514919.13,
                'ana_modificaciones'   => 34715.87,
                'analitico_version_id' => 78,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbF63Q',
                'ana_monto'            => 150145.28,
                'ana_modificaciones'   => -21724.99,
                'analitico_version_id' => 78,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbF63R',
                'ana_monto'            => 1208212.96,
                'ana_modificaciones'   => 2308936.31,
                'analitico_version_id' => 78,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbJu9F',
                'ana_monto'            => 15100.00,
                'ana_modificaciones'   => 0.00,
                'analitico_version_id' => 78,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbJu9G',
                'ana_monto'            => 22600.00,
                'ana_modificaciones'   => 3600.00,
                'analitico_version_id' => 78,
            ],
            [
                'ana_act_proy'         => 2130855,
                'ana_componente'       => 6000016,
                'ana_especifca'        => 'ACbJvAN',
                'ana_monto'            => 7670.00,
                'ana_modificaciones'   => 851.49,
                'analitico_version_id' => 78,
            ],
        ]);

        //analítico version
        DB::table('proy_analitico_version')->insert([
            [
                'vers_proyecto'    => 2130855,
                'vers_version'     => 1,
                'vers_responzable' => 2,
                'vers_cargo'       => 'Asistente administrativo',
                'vers_observacion' => 'SE TRABAJO CON MONTO DE COMPONENTES EXISTENTES EN EL INVIERTE.PE',
            ],
            [
                'vers_proyecto'    => 2130855,
                'vers_version'     => 2,
                'vers_responzable' => 2,
                'vers_cargo'       => 'Especialista administrativo',
                'vers_observacion' => 'SE TRABAJO CON R.E.R. N° 858-2017-GRH/GRI - QUE APRUEBA EL PRESUPUESTO ANALITICO DE GASTOS ADMINISTRATIVOS DEL PROYECTO',
            ],
            [
                'vers_proyecto'    => 2130855,
                'vers_version'     => 3,
                'vers_responzable' => 2,
                'vers_cargo'       => 'Especialista administrativo',
                'vers_observacion' => 'SE TIENE EN CONSIDERACION LA R.G.R. N° 858-2017-GRH/GRI DE APROBACION DE LOS GASTOS DE GENERALES Y MODIFICACIONES ',
            ],
        ]);
        //obra
        DB::table('proy_obra')->insert([
            [
                'proy_proyecto_idproy_proyecto'          => 1,
                'obr_vinculo'                            => 1112,
                'obr_estado'                             => 5,
                'obr_nombre'                             => 'OBRA: MEJORAMIENTO DE LA CAPACIDAD RESOLUTIVA DEL HOSPITAL DE TINGO MARIA - PROVINCIA LEONCIO PRADO - REGION HUANUCO',
                'obr_beneficiarios'                      => 42115,
                'distrito_dis_codigo'                    => 578,
                'obr_componentes_metas'                  => 'DEMOLICION MODULO EXISTENTE DEL HOSPITAL TINGO MARIA',
                'obr_tipo_proceso'                       => null,
                'obr_proceso_seleccion'                  => 'LP 5-2012-GRH',
                'obr_valor_referencial'                  => 101151243.01,
                'obr_modalidad_ejecucion'                => '2',
                'obr_monto_contrato'                     => 101149888.71,
                'obr_fecha_contrato'                     => '2013-04-19',
                'obr_plazo'                              => 660,
                'obr_fecha_inicio_ejecucion'             => '2013-11-09',
                'obr_contrato_ejecucion'                 => '334-2013-GRH/GR',
                'obr_direccion_ejecutor'                 => 'AV UCAYALI No. 114 - PUERTA No. 01 - TINGO MARIA',
                'obr_car_fia_fiel_cumplimiento_requiere' => 1,
                'obr_car_fia_adelanto_directo_requiere'  => 0,
                'obr_car_fia_adelanto_material_requiere' => 0,
                'obr_nombre_ejecutor'                    => 'CONSORCIO EJECUTOR TINGO MARIA',
                'obr_representante_ejecutor'             => 'ALVARO HUIDOBRO BUSTAMANTE/EMAGOR TESSINARI FILHOE',
                'obr_fr'                                 => 0.00000,
                'regulation_idregulation'                => 47607,
                'obr_vigente'                            => 1,
                'obr_tipo_contrato'                      => 2,
                'obr_contratista_ruc'                    => null,
                'obr_contrato_principal'                 => 1,
            ],
            [
                'proy_proyecto_idproy_proyecto'          => 1,
                'obr_vinculo'                            => null,
                'obr_estado'                             => null,
                'obr_nombre'                             => 'CONTRATACION DE SERVICIOS DE CONSULTORIA PARA LA SUPERVISION DE LA ELABORACION DEL EXPEDIENTE TECNICO DEL PROYECTO: MEJORAMIENTO DE LA CAPACIDAD RESOLUTIVA DEL HOSPITAL DE TINGO MARIA',
                'obr_beneficiarios'                      => null,
                'distrito_dis_codigo'                    => null,
                'obr_componentes_metas'                  => null,
                'obr_tipo_proceso'                       => 'ADJUDICACION DE MENOR CUANTIA',
                'obr_proceso_seleccion'                  => null,
                'obr_valor_referencial'                  => null,
                'obr_modalidad_ejecucion'                => null,
                'obr_monto_contrato'                     => 256460.11,
                'obr_fecha_contrato'                     => '2011-11-17',
                'obr_plazo'                              => 0,
                'obr_fecha_inicio_ejecucion'             => null,
                'obr_contrato_ejecucion'                 => '537-2011-GRH/PR',
                'obr_direccion_ejecutor'                 => null,
                'obr_car_fia_fiel_cumplimiento_requiere' => null,
                'obr_car_fia_adelanto_directo_requiere'  => null,
                'obr_car_fia_adelanto_material_requiere' => null,
                'obr_nombre_ejecutor'                    => 'MATOS VEJARANO GERARDO MARTIN',
                'obr_representante_ejecutor'             => null,
                'obr_fr'                                 => 0.00000,
                'regulation_idregulation'                => null,
                'obr_vigente'                            => 0,
                'obr_tipo_contrato'                      => 3,
                'obr_contratista_ruc'                    => '10102092380',
                'obr_contrato_principal'                 => 0,
            ],
            [
                'proy_proyecto_idproy_proyecto'          => 1,
                'obr_vinculo'                            => null,
                'obr_estado'                             => null,
                'obr_nombre'                             => 'MONITOR EN PROCESOS DE SELECCIN. PRO.: MEJORAM. DE LA CAPACIDAD RESOLUTIVA DEL HOSPITAL DE TINGO MARIA HCO.',
                'obr_beneficiarios'                      => null,
                'distrito_dis_codigo'                    => null,
                'obr_componentes_metas'                  => null,
                'obr_tipo_proceso'                       => 'ADJUDICACION DE MENOR CUANTIA',
                'obr_proceso_seleccion'                  => null,
                'obr_valor_referencial'                  => null,
                'obr_modalidad_ejecucion'                => null,
                'obr_monto_contrato'                     => 39990.00,
                'obr_fecha_contrato'                     => '2014-03-12',
                'obr_plazo'                              => 0,
                'obr_fecha_inicio_ejecucion'             => null,
                'obr_contrato_ejecucion'                 => '178-2014-GRH/PR',
                'obr_direccion_ejecutor'                 => null,
                'obr_car_fia_fiel_cumplimiento_requiere' => null,
                'obr_car_fia_adelanto_directo_requiere'  => null,
                'obr_car_fia_adelanto_material_requiere' => null,
                'obr_nombre_ejecutor'                    => 'PONCE GONZALEZ OSCAR WILFREDO',
                'obr_representante_ejecutor'             => null,
                'obr_fr'                                 => 0.00000,
                'regulation_idregulation'                => null,
                'obr_vigente'                            => 0,
                'obr_tipo_contrato'                      => 99,
                'obr_contratista_ruc'                    => '10199240965',
                'obr_contrato_principal'                 => 0,
            ],
            [
                'proy_proyecto_idproy_proyecto'          => 1,
                'obr_vinculo'                            => 604,
                'obr_estado'                             => 5,
                'obr_nombre'                             => 'CP N 001-2013/GRH Contratacion de los Servicios de Consultoria de Obra Para la Supervision del Proyecto: Mejoramiento de la Capacidad Resolutiva del Hospital de Tingo Maria.CONTRATO N 431-2013-GRH/PR',
                'obr_beneficiarios'                      => null,
                'distrito_dis_codigo'                    => null,
                'obr_componentes_metas'                  => null,
                'obr_tipo_proceso'                       => 'CONCURSO PUBLICO',
                'obr_proceso_seleccion'                  => 'CP N 001-2013/GRH',
                'obr_valor_referencial'                  => 3034537.29,
                'obr_modalidad_ejecucion'                => 2,
                'obr_monto_contrato'                     => 3034537.29,
                'obr_fecha_contrato'                     => '2013-05-17',
                'obr_plazo'                              => 600,
                'obr_fecha_inicio_ejecucion'             => '2013-11-11',
                'obr_contrato_ejecucion'                 => '431-2013-GRH/PR',
                'obr_direccion_ejecutor'                 => 'Av. Javier Prado N 3092',
                'obr_car_fia_fiel_cumplimiento_requiere' => 0,
                'obr_car_fia_adelanto_directo_requiere'  => 0,
                'obr_car_fia_adelanto_material_requiere' => 0,
                'obr_nombre_ejecutor'                    => 'ACRUTA & TAPIA INGENIEROS S.A.C.',
                'obr_representante_ejecutor'             => 'Elias Tapia Julca',
                'obr_fr'                                 => 0.00000,
                'regulation_idregulation'                => null,
                'obr_vigente'                            => 1,
                'obr_tipo_contrato'                      => 3,
                'obr_contratista_ruc'                    => '20262241441',
                'obr_contrato_principal'                 => 0,
            ],
            [
                'proy_proyecto_idproy_proyecto'          => 1,
                'obr_vinculo'                            => null,
                'obr_estado'                             => null,
                'obr_nombre'                             => 'SUMINISTRO DE COMBUSTIBLE GASOHOL 90 PLUS PARA TRABAJOS DE MONITOREO TECNICO DE OBRAS A CARGO DE LA SUB GERENCIA DE SUPERVISION Y LIQUIDACION',
                'obr_beneficiarios'                      => null,
                'distrito_dis_codigo'                    => null,
                'obr_componentes_metas'                  => null,
                'obr_tipo_proceso'                       => 'ADJUDICACION DE MENOR CUANTIA',
                'obr_proceso_seleccion'                  => null,
                'obr_valor_referencial'                  => null,
                'obr_modalidad_ejecucion'                => null,
                'obr_monto_contrato'                     => 76932.99,
                'obr_fecha_contrato'                     => '2013-06-25',
                'obr_plazo'                              => 0,
                'obr_fecha_inicio_ejecucion'             => null,
                'obr_contrato_ejecucion'                 => '547-2013-GRH/PR',
                'obr_direccion_ejecutor'                 => null,
                'obr_car_fia_fiel_cumplimiento_requiere' => null,
                'obr_car_fia_adelanto_directo_requiere'  => null,
                'obr_car_fia_adelanto_material_requiere' => null,
                'obr_nombre_ejecutor'                    => 'COMERCIALIZADORA DE COMBUSTIBLE DELTA E.I.R.L.',
                'obr_representante_ejecutor'             => null,
                'obr_fr'                                 => 0.00000,
                'regulation_idregulation'                => null,
                'obr_vigente'                            => 0,
                'obr_tipo_contrato'                      => 99,
                'obr_contratista_ruc'                    => '20528970339',
                'obr_contrato_principal'                 => 0,
            ],
            [
                'proy_proyecto_idproy_proyecto'          => 1,
                'obr_vinculo'                            => null,
                'obr_estado'                             => 5,
                'obr_nombre'                             => 'CONTRATACION DE SERVICIOS DE CONSULTORIA PARA ELABORACION DEL EXPEDIENTE TECNICO DEL PROY: MEJORAMIENTO DE LA CAPACIDAD RESOLUTIVA DEL HOSPITAL DE TINGO MARIA',
                'obr_beneficiarios'                      => null,
                'distrito_dis_codigo'                    => null,
                'obr_componentes_metas'                  => null,
                'obr_tipo_proceso'                       => 'CONCURSO PUBLICO',
                'obr_proceso_seleccion'                  => null,
                'obr_valor_referencial'                  => null,
                'obr_modalidad_ejecucion'                => null,
                'obr_monto_contrato'                     => 2607756.00,
                'obr_fecha_contrato'                     => '2011-08-26',
                'obr_plazo'                              => 0,
                'obr_fecha_inicio_ejecucion'             => null,
                'obr_contrato_ejecucion'                 => '356-2011/GRH/PR',
                'obr_direccion_ejecutor'                 => null,
                'obr_car_fia_fiel_cumplimiento_requiere' => 0,
                'obr_car_fia_adelanto_directo_requiere'  => 0,
                'obr_car_fia_adelanto_material_requiere' => 0,
                'obr_nombre_ejecutor'                    => 'CONSORCIO PROYECTO HOSPITAL DE TINGO MARIA',
                'obr_representante_ejecutor'             => null,
                'obr_fr'                                 => 0.00000,
                'regulation_idregulation'                => null,
                'obr_vigente'                            => 1,
                'obr_tipo_contrato'                      => 1,
                'obr_contratista_ruc'                    => '20544580966',
                'obr_contrato_principal'                 => 0,
            ],
        ]);
        DB::table('proy_obra')->insert([
            [
                'proy_proyecto_idproy_proyecto'          => 2,
                'obr_vinculo'                            => null,
                'obr_estado'                             => 5,
                'obr_nombre'                             => 'MEJORAMIENTO DE LA CAPACIDAD RESOLUTIVA DE LOS SERVICIOS DE SALUD DEL HOSPITAL REGIONAL HERMILIO VALDIZAN DE HUANUCO-NIVEL III-1, ITEM 2: EJECUCION DEL PLAN DE CONTINGENCIA.3',
                'obr_beneficiarios'                      => 780411,
                'distrito_dis_codigo'                    => 621,
                'obr_componentes_metas'                  => 'Los Ambientes contenidos en los diversos Modulos se detallan a continuacion :',
                'obr_tipo_proceso'                       => null,
                'obr_proceso_seleccion'                  => null,
                'obr_valor_referencial'                  => 10000000.00,
                'obr_modalidad_ejecucion'                => '2',
                'obr_monto_contrato'                     => 9999999.00,
                'obr_fecha_contrato'                     => '2014-08-11',
                'obr_plazo'                              => 120,
                'obr_fecha_inicio_ejecucion'             => '2014-10-30',
                'obr_contrato_ejecucion'                 => '584-2014-GRH/PR',
                'obr_direccion_ejecutor'                 => 'CALLE 1 SAN JUAN BOSCO - CALLE 2 SAN BENITO',
                'obr_car_fia_fiel_cumplimiento_requiere' => 1,
                'obr_car_fia_adelanto_directo_requiere'  => 0,
                'obr_car_fia_adelanto_material_requiere' => 0,
                'obr_nombre_ejecutor'                    => 'CONSORCIO HUANUCO SALUD',
                'obr_representante_ejecutor'             => 'ING. RAFAEL  RODRIGUEZ MUÑOZ',
                'obr_fr'                                 => 0.00000,
                'regulation_idregulation'                => null,
                'obr_vigente'                            => 0,
                'obr_tipo_contrato'                      => 2,
                'obr_contratista_ruc'                    => null,
                'obr_contrato_principal'                 => 0,
            ],
            [
                'proy_proyecto_idproy_proyecto'          => 2,
                'obr_vinculo'                            => null,
                'obr_estado'                             => 9,
                'obr_nombre'                             => 'SERV. CONSULTORIA PARA ELABORACION DEL EXPEDIENTE TECNICO. PROY: MEJORAM. DE CAPACIDAD RESOLUTIVA DE LOS SERVICIOS DE SALUD H.R.H. VALDIZAN HUANUCO NIVEL III-1.',
                'obr_beneficiarios'                      => null,
                'distrito_dis_codigo'                    => null,
                'obr_componentes_metas'                  => null,
                'obr_tipo_proceso'                       => 'ADJUDICACION DIRECTA SELECTIVA',
                'obr_proceso_seleccion'                  => null,
                'obr_valor_referencial'                  => null,
                'obr_modalidad_ejecucion'                => null,
                'obr_monto_contrato'                     => 171000.00,
                'obr_fecha_contrato'                     => '2013-05-17',
                'obr_plazo'                              => 0,
                'obr_fecha_inicio_ejecucion'             => null,
                'obr_contrato_ejecucion'                 => '434-2013-GRH/PR',
                'obr_direccion_ejecutor'                 => null,
                'obr_car_fia_fiel_cumplimiento_requiere' => 0,
                'obr_car_fia_adelanto_directo_requiere'  => 0,
                'obr_car_fia_adelanto_material_requiere' => 0,
                'obr_nombre_ejecutor'                    => 'TURZA AREVALO GUILLERMO ANDRES',
                'obr_representante_ejecutor'             => null,
                'obr_fr'                                 => 0.00000,
                'regulation_idregulation'                => null,
                'obr_vigente'                            => 1,
                'obr_tipo_contrato'                      => 1,
                'obr_contratista_ruc'                    => '10071936444',
                'obr_contrato_principal'                 => 0,
            ],
            [
                'proy_proyecto_idproy_proyecto'          => 2,
                'obr_vinculo'                            => null,
                'obr_estado'                             => null,
                'obr_nombre'                             => 'CONTRATACION DE SERVICIOS DE CONSULTORIA PARA LA ELABORACION DEL EXPEDIENTE TECNICO DEL PROYECTO: CONSTRUCCION Y EQUIPAMIENTO DEL HOSPITAL REGIONAL HERMILIO VALDIZAN DE HUANUCO III- A',
                'obr_beneficiarios'                      => null,
                'distrito_dis_codigo'                    => null,
                'obr_componentes_metas'                  => null,
                'obr_tipo_proceso'                       => 'CONCURSO PUBLICO',
                'obr_proceso_seleccion'                  => null,
                'obr_valor_referencial'                  => null,
                'obr_modalidad_ejecucion'                => null,
                'obr_monto_contrato'                     => 1900000.01,
                'obr_fecha_contrato'                     => '2012-12-05',
                'obr_plazo'                              => 0,
                'obr_fecha_inicio_ejecucion'             => null,
                'obr_contrato_ejecucion'                 => '1009-2012-GRH/PR',
                'obr_direccion_ejecutor'                 => null,
                'obr_car_fia_fiel_cumplimiento_requiere' => null,
                'obr_car_fia_adelanto_directo_requiere'  => null,
                'obr_car_fia_adelanto_material_requiere' => null,
                'obr_nombre_ejecutor'                    => 'CONSORCIO HOSPITALARIO HUANUCO',
                'obr_representante_ejecutor'             => null,
                'obr_fr'                                 => 0.00000,
                'regulation_idregulation'                => null,
                'obr_vigente'                            => 0,
                'obr_tipo_contrato'                      => 1,
                'obr_contratista_ruc'                    => '20550588812',
                'obr_contrato_principal'                 => 0,
            ],
            [
                'proy_proyecto_idproy_proyecto'          => 2,
                'obr_vinculo'                            => 2086,
                'obr_estado'                             => 0,
                'obr_nombre'                             => 'EJECUCION DE OBRA: MEJORAMIENTO DE LA CAPACIDAD RESOLUTIVA DE LOS SERVICIOS DE SALUD DEL HOSPITAL REGIONAL HERMILIO VALDIZAN DE HUANUCO NIVEL III-1 (ITEM 1: EJECUCION DE OBRA PRINCIPAL Y EQUIPAMIENTO).',
                'obr_beneficiarios'                      => null,
                'distrito_dis_codigo'                    => null,
                'obr_componentes_metas'                  => null,
                'obr_tipo_proceso'                       => 'CONVENIO',
                'obr_proceso_seleccion'                  => 'INTERNACIONAL PSI N 01-024-OEI-GRH',
                'obr_valor_referencial'                  => 162256602.55,
                'obr_modalidad_ejecucion'                => '2',
                'obr_monto_contrato'                     => 162256602.55,
                'obr_fecha_contrato'                     => '2014-06-24',
                'obr_plazo'                              => 548,
                'obr_fecha_inicio_ejecucion'             => '2017-06-01',
                'obr_contrato_ejecucion'                 => '425-2014-GRH/GR',
                'obr_direccion_ejecutor'                 => 'JR CONSTITUCION CDRA. 8, HUANUCO, HUANUCO.',
                'obr_car_fia_fiel_cumplimiento_requiere' => 0,
                'obr_car_fia_adelanto_directo_requiere'  => 0,
                'obr_car_fia_adelanto_material_requiere' => 0,
                'obr_nombre_ejecutor'                    => 'CONSORCIO OBRAINSA - JOCA',
                'obr_representante_ejecutor'             => 'FEDERICO ALEJANDRO TEJEDA MOSCOSO',
                'obr_fr'                                 => 0.00000,
                'regulation_idregulation'                => 46331,
                'obr_vigente'                            => 0,
                'obr_tipo_contrato'                      => 2,
                'obr_contratista_ruc'                    => '20562849581',
                'obr_contrato_principal'                 => 0,
            ],
            [
                'proy_proyecto_idproy_proyecto'          => 2,
                'obr_vinculo'                            => null,
                'obr_estado'                             => 5,
                'obr_nombre'                             => 'SUPERVISION EJEC. PLAN CONTINGENCIA. PROY.: MEJORAM. CAPACIDAD RESOLUTIVA Ss. DE SALUD HOSPITAL REGIONAL HERMILIO VALDIZAN DE HUANUCO NIVEL III-1.',
                'obr_beneficiarios'                      => null,
                'distrito_dis_codigo'                    => null,
                'obr_componentes_metas'                  => null,
                'obr_tipo_proceso'                       => 'ADJUDICACION DIRECTA PUBLICA',
                'obr_proceso_seleccion'                  => null,
                'obr_valor_referencial'                  => null,
                'obr_modalidad_ejecucion'                => null,
                'obr_monto_contrato'                     => 380000.00,
                'obr_fecha_contrato'                     => '2014-10-14',
                'obr_plazo'                              => 120,
                'obr_fecha_inicio_ejecucion'             => null,
                'obr_contrato_ejecucion'                 => '803-2014-GRH/PR',
                'obr_direccion_ejecutor'                 => null,
                'obr_car_fia_fiel_cumplimiento_requiere' => 0,
                'obr_car_fia_adelanto_directo_requiere'  => 0,
                'obr_car_fia_adelanto_material_requiere' => 0,
                'obr_nombre_ejecutor'                    => 'ING. JONY ARQUIGO TRUJILLO',
                'obr_representante_ejecutor'             => null,
                'obr_fr'                                 => 0.00000,
                'regulation_idregulation'                => null,
                'obr_vigente'                            => 0,
                'obr_tipo_contrato'                      => 3,
                'obr_contratista_ruc'                    => '20573317808',
                'obr_contrato_principal'                 => 0,
            ],
            [
                'proy_proyecto_idproy_proyecto'          => 2,
                'obr_vinculo'                            => null,
                'obr_estado'                             => 9,
                'obr_nombre'                             => 'INSPECCION :"MEJORAMIENTO DE LA CAPACIDAD RESOLUTIVA DE LOS SERVICIOS DE SALUD DEL HOSPITAL REGIONAL HERMILIO VALDIZAN DE HUANUCO-NIVEL III-1"',
                'obr_beneficiarios'                      => null,
                'distrito_dis_codigo'                    => null,
                'obr_componentes_metas'                  => null,
                'obr_tipo_proceso'                       => null,
                'obr_proceso_seleccion'                  => null,
                'obr_valor_referencial'                  => null,
                'obr_modalidad_ejecucion'                => '2',
                'obr_monto_contrato'                     => null,
                'obr_fecha_contrato'                     => '2015-02-26',
                'obr_plazo'                              => 120,
                'obr_fecha_inicio_ejecucion'             => null,
                'obr_contrato_ejecucion'                 => null,
                'obr_direccion_ejecutor'                 => null,
                'obr_car_fia_fiel_cumplimiento_requiere' => 0,
                'obr_car_fia_adelanto_directo_requiere'  => 0,
                'obr_car_fia_adelanto_material_requiere' => 0,
                'obr_nombre_ejecutor'                    => 'ING. JUAN CARLOS GARCIA',
                'obr_representante_ejecutor'             => null,
                'obr_fr'                                 => 0.00000,
                'regulation_idregulation'                => null,
                'obr_vigente'                            => 1,
                'obr_tipo_contrato'                      => 3,
                'obr_contratista_ruc'                    => null,
                'obr_contrato_principal'                 => 0,
            ],
            [
                'proy_proyecto_idproy_proyecto'          => 2,
                'obr_vinculo'                            => null,
                'obr_estado'                             => 0,
                'obr_nombre'                             => 'Contrato de Consultori­a para la supervision de la Elaboracion del Expediente tecnico del Proyecto: "Mejoramiento de la Capacidad Resolutiva de los servicios de Salud del Hospital Regional Hermilio Valdizan de Huanuco"',
                'obr_beneficiarios'                      => null,
                'distrito_dis_codigo'                    => null,
                'obr_componentes_metas'                  => null,
                'obr_tipo_proceso'                       => null,
                'obr_proceso_seleccion'                  => null,
                'obr_valor_referencial'                  => null,
                'obr_modalidad_ejecucion'                => null,
                'obr_monto_contrato'                     => null,
                'obr_fecha_contrato'                     => null,
                'obr_plazo'                              => 0,
                'obr_fecha_inicio_ejecucion'             => null,
                'obr_contrato_ejecucion'                 => null,
                'obr_direccion_ejecutor'                 => null,
                'obr_car_fia_fiel_cumplimiento_requiere' => 0,
                'obr_car_fia_adelanto_directo_requiere'  => 0,
                'obr_car_fia_adelanto_material_requiere' => 0,
                'obr_nombre_ejecutor'                    => 'GUILLERMO ANDRES',
                'obr_representante_ejecutor'             => null,
                'obr_fr'                                 => 0.00000,
                'regulation_idregulation'                => null,
                'obr_vigente'                            => 0,
                'obr_tipo_contrato'                      => 99,
                'obr_contratista_ruc'                    => null,
                'obr_contrato_principal'                 => 0,
            ],
            [
                'proy_proyecto_idproy_proyecto'          => 2,
                'obr_vinculo'                            => null,
                'obr_estado'                             => 0,
                'obr_nombre'                             => 'ADP N 038-2015-GRH/GR (PRIMERA CONVOCATORIA) CONTRATACION DEL SERVICIO DE ADMINISTRADORES DE CONTRATOS PARA LA EJECUCION DE LA OBRA:MEJORAMIENTO DE LA CAPACIDAD RESOLUTIVA',
                'obr_beneficiarios'                      => null,
                'distrito_dis_codigo'                    => null,
                'obr_componentes_metas'                  => null,
                'obr_tipo_proceso'                       => null,
                'obr_proceso_seleccion'                  => null,
                'obr_valor_referencial'                  => null,
                'obr_modalidad_ejecucion'                => null,
                'obr_monto_contrato'                     => null,
                'obr_fecha_contrato'                     => null,
                'obr_plazo'                              => 0,
                'obr_fecha_inicio_ejecucion'             => null,
                'obr_contrato_ejecucion'                 => null,
                'obr_direccion_ejecutor'                 => null,
                'obr_car_fia_fiel_cumplimiento_requiere' => 0,
                'obr_car_fia_adelanto_directo_requiere'  => 0,
                'obr_car_fia_adelanto_material_requiere' => 0,
                'obr_nombre_ejecutor'                    => 'NABOR ARTURO SALAZAR',
                'obr_representante_ejecutor'             => null,
                'obr_fr'                                 => 0.00000,
                'regulation_idregulation'                => null,
                'obr_vigente'                            => 0,
                'obr_tipo_contrato'                      => 99,
                'obr_contratista_ruc'                    => null,
                'obr_contrato_principal'                 => 0,
            ],
            [
                'proy_proyecto_idproy_proyecto'          => 2,
                'obr_vinculo'                            => null,
                'obr_estado'                             => 0,
                'obr_nombre'                             => 'SERVICIO DE ADMINISTRADOR DE CONTRATOS PARA LA EJECUCION DE LA OBRA:MEJORAMIENTO DE LA CAPACIDAD RESOLUTIVA DE LOS SERVICIOS DE SALUD DEL HOSPITAL REGIONAL HERMILIO VALDIZAN DE HUANUCO  NIVEL 111 - 1',
                'obr_beneficiarios'                      => null,
                'distrito_dis_codigo'                    => null,
                'obr_componentes_metas'                  => null,
                'obr_tipo_proceso'                       => null,
                'obr_proceso_seleccion'                  => null,
                'obr_valor_referencial'                  => null,
                'obr_modalidad_ejecucion'                => null,
                'obr_monto_contrato'                     => null,
                'obr_fecha_contrato'                     => null,
                'obr_plazo'                              => 0,
                'obr_fecha_inicio_ejecucion'             => null,
                'obr_contrato_ejecucion'                 => null,
                'obr_direccion_ejecutor'                 => null,
                'obr_car_fia_fiel_cumplimiento_requiere' => 0,
                'obr_car_fia_adelanto_directo_requiere'  => 0,
                'obr_car_fia_adelanto_material_requiere' => 0,
                'obr_nombre_ejecutor'                    => 'ROSA AMELIA KOHAMA',
                'obr_representante_ejecutor'             => null,
                'obr_fr'                                 => 0.00000,
                'regulation_idregulation'                => null,
                'obr_vigente'                            => 0,
                'obr_tipo_contrato'                      => 99,
                'obr_contratista_ruc'                    => null,
                'obr_contrato_principal'                 => 0,
            ],
            [
                'proy_proyecto_idproy_proyecto'          => 2,
                'obr_vinculo'                            => null,
                'obr_estado'                             => 9,
                'obr_nombre'                             => 'MEJORAMIENTO DE LA CAPACIDAD RESOLUTIVA DE LOS SERVICIOS DE SALUD DEL HOSPITAL REGIONAL HERMILIO VALDIZAN DE HUANUCO-NIVEL III-1 (MODALIDAD ADMINISTRACION DIRECTA)',
                'obr_beneficiarios'                      => null,
                'distrito_dis_codigo'                    => null,
                'obr_componentes_metas'                  => null,
                'obr_tipo_proceso'                       => null,
                'obr_proceso_seleccion'                  => null,
                'obr_valor_referencial'                  => null,
                'obr_modalidad_ejecucion'                => '1',
                'obr_monto_contrato'                     => 4431406.80,
                'obr_fecha_contrato'                     => '2016-06-10',
                'obr_plazo'                              => 264,
                'obr_fecha_inicio_ejecucion'             => '2016-06-10',
                'obr_contrato_ejecucion'                 => null,
                'obr_direccion_ejecutor'                 => null,
                'obr_car_fia_fiel_cumplimiento_requiere' => null,
                'obr_car_fia_adelanto_directo_requiere'  => null,
                'obr_car_fia_adelanto_material_requiere' => null,
                'obr_nombre_ejecutor'                    => 'ADMINISTRACION DIRECTA',
                'obr_representante_ejecutor'             => null,
                'obr_fr'                                 => 0.00000,
                'regulation_idregulation'                => null,
                'obr_vigente'                            => 1,
                'obr_tipo_contrato'                      => 2,
                'obr_contratista_ruc'                    => null,
                'obr_contrato_principal'                 => 0,
            ],
            [
                'proy_proyecto_idproy_proyecto'          => 2,
                'obr_vinculo'                            => 1128,
                'obr_estado'                             => 5,
                'obr_nombre'                             => 'CONVENIO ESPECIFICO DE COOPERACION INTERINSTITUCIONAL ENTRE EL GOBIERNO REGIONAL DE HUANUCO Y LA UNIVERSIDAD NACIONAL HERMILIO VALDIZAN DE HUANUCO PARA LA SUPERVISION DE LA EJECUCION DE LA OBRA MEJORAMIENTO',
                'obr_beneficiarios'                      => null,
                'distrito_dis_codigo'                    => null,
                'obr_componentes_metas'                  => null,
                'obr_tipo_proceso'                       => null,
                'obr_proceso_seleccion'                  => 'CONVENIO DE COOPERACION INTERINSTITUCIONAL',
                'obr_valor_referencial'                  => 0.00,
                'obr_modalidad_ejecucion'                => '2',
                'obr_monto_contrato'                     => 5005170.00,
                'obr_fecha_contrato'                     => '2015-11-12',
                'obr_plazo'                              => 549,
                'obr_fecha_inicio_ejecucion'             => '2017-06-01',
                'obr_contrato_ejecucion'                 => 'CONVENIO N 007-2015',
                'obr_direccion_ejecutor'                 => 'JR. DOS DE MAYO N 685',
                'obr_car_fia_fiel_cumplimiento_requiere' => 0,
                'obr_car_fia_adelanto_directo_requiere'  => 0,
                'obr_car_fia_adelanto_material_requiere' => 0,
                'obr_nombre_ejecutor'                    => 'UNE',
                'obr_representante_ejecutor'             => 'ING. JORGE ',
                'obr_fr'                                 => 0.00000,
                'regulation_idregulation'                => null,
                'obr_vigente'                            => 0,
                'obr_tipo_contrato'                      => 3,
                'obr_contratista_ruc'                    => null,
                'obr_contrato_principal'                 => 0,
            ],

        ]);
    }
}
